2025-03-05 14:56:40,732 - messaging - INFO - performance_logger.py:20 - LATENCY: rabbitmq_connection took 80.11ms
2025-03-05 14:56:40,734 - messaging - INFO - subscriber.py:81 - Successfully connected to RabbitMQ
2025-03-05 14:56:40,751 - messaging - INFO - subscriber.py:121 - Started consuming messages from RabbitMQ
2025-03-05 14:56:54,336 - messaging - INFO - subscriber.py:97 - Received move: {'from_square': 'g8', 'to_square': 'h6', 'message_id': '4ea8275f', 'timestamp': 1741186614.3326735}
2025-03-05 14:56:54,339 - messaging - INFO - performance_logger.py:20 - LATENCY: message_delivery took 6.66ms
2025-03-05 14:56:54,367 - messaging - INFO - subscriber.py:97 - Received move: {'from_square': 'f7', 'to_square': 'f5', 'message_id': 'acd0769e', 'timestamp': 1741186614.3348088}
2025-03-05 14:56:54,369 - messaging - INFO - performance_logger.py:20 - LATENCY: message_delivery took 35.08ms
2025-03-05 14:56:54,486 - messaging - INFO - performance_logger.py:31 - MOVE: g8h6 FAILURE
2025-03-05 14:56:54,487 - messaging - ERROR - performance_logger.py:35 - ERROR: movement - execution_failure: Move g8h6
2025-03-05 14:56:54,675 - messaging - INFO - performance_logger.py:31 - MOVE: f7f5 FAILURE
2025-03-05 14:56:54,675 - messaging - ERROR - performance_logger.py:35 - ERROR: movement - execution_failure: Move f7f5
2025-03-05 14:58:43,163 - messaging - ERROR - subscriber.py:187 - Error during cleanup: Stream connection lost: IndexError('pop from an empty deque')
2025-03-05 14:58:43,164 - messaging - ERROR - subscriber.py:125 - RabbitMQ consuming error: Stream connection lost: IndexError('pop from an empty deque')
